//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab5.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Demo_Lab5Entities : DbContext
    {
        public Demo_Lab5Entities()
            : base("name=Demo_Lab5Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<HISTORY> HISTORies { get; set; }
        public DbSet<THANHVIEN> THANHVIENs { get; set; }
        public DbSet<YEUTHICH> YEUTHICHes { get; set; }
    }
}
